INSERT INTO regions (name) VALUES('Africa');
INSERT INTO regions (name) VALUES('Asia');
INSERT INTO regions (name) VALUES('Caribbean');
INSERT INTO regions (name) VALUES('Central America');
INSERT INTO regions (name) VALUES('Europe');
INSERT INTO regions (name) VALUES('North America');
INSERT INTO regions (name) VALUES('Oceania');
INSERT INTO regions (name) VALUES('South America');

INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', 1, '2018-01-02');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', 1, '2018-01-03');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', 4, '2018-01-04');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', 5, '2018-02-01');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', 1, '2018-02-10');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', 1, '2018-02-18');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', 1, '2018-02-28');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', 2, '2018-03-03');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', 1, '2018-03-04');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', 2, '2018-03-05');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', 5, '2018-03-06');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Mr. John', 'Doe', 'john.doe2@gmail.com', 1, '2018-01-02');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Linus', 'Torvalds', 'linus.torvalds2@gmail.com', 1, '2018-01-03');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf2@gmail.com', 5, '2018-01-04');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Erich', 'Gamma', 'erich.gamma2@gmail.com', 6, '2018-02-01');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Richard', 'Helm', 'richard.helm2@gmail.com', 2, '2018-02-10');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Ralph', 'Johnson', 'ralph.johnson2@gmail.com', 1, '2018-02-18');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('John', 'Vlissides', 'john.vlissides2@gmail.com', 1, '2018-02-28');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Dr. James', 'Gosling', 'james.gosling2@gmail.com', 6, '2018-03-03');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Magma', 'Lee', 'magma.lee2@gmail.com', 2, '2018-03-04');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Tornado', 'Roe', 'tornado.roe2@gmail.com', 7, '2018-03-05');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Jade', 'Doe', 'jane.doe2@gmail.com', 1, '2018-03-06');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Mr. John', 'Doe', 'john.doe3@gmail.com', 1, '2018-01-02');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Linus', 'Torvalds', 'linus.torvalds3@gmail.com', 2, '2018-01-03');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf3@gmail.com', 7, '2018-01-04');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Erich', 'Gamma', 'erich.gamma3@gmail.com', 1, '2018-02-01');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Richard', 'Helm', 'richard.helm3@gmail.com', 1, '2018-02-10');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Ralph', 'Johnson', 'ralph.johnson3@gmail.com', 7, '2018-02-18');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('John', 'Vlissides', 'john.vlissides3@gmail.com', 2, '2018-02-28');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Dr. James', 'Gosling', 'james.gosling3@gmail.com', 1, '2018-03-03');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Magma', 'Lee', 'magma.lee3@gmail.com', 7, '2018-03-04');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Tornado', 'Roe', 'tornado.roe3@gmail.com', 1, '2018-03-05');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Jade', 'Doe', 'jane.doe3@gmail.com', 2, '2018-03-06');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Mr. John', 'Doe', 'john.doe4@gmail.com', 1, '2018-01-02');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Linus', 'Torvalds', 'linus.torvalds4@gmail.com', 8, '2018-01-03');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf4@gmail.com', 1, '2018-01-04');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Erich', 'Gamma', 'erich.gamma4@gmail.com', 8, '2018-02-01');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Richard', 'Helm', 'richard.helm4@gmail.com', 2, '2018-02-10');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Ralph', 'Johnson', 'ralph.johnson4@gmail.com', 1, '2018-02-18');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('John', 'Vlissides', 'john.vlissides4@gmail.com', 1, '2018-02-28');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Dr. James', 'Gosling', 'james.gosling4@gmail.com', 3, '2018-03-03');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Magma', 'Lee', 'magma.lee4@gmail.com', 8, '2018-03-04');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Tornado', 'Roe', 'tornado.roe4@gmail.com', 1, '2018-03-05');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Jade', 'Doe', 'jane.doe4@gmail.com', 3, '2018-03-06');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Mr. John', 'Doe', 'john.doe5@gmail.com', 1, '2018-01-02');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Linus', 'Torvalds', 'linus.torvalds5@gmail.com', 8, '2018-01-03');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf5@gmail.com', 3, '2018-01-04');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Erich', 'Gamma', 'erich.gamma5@gmail.com', 1, '2018-02-01');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Richard', 'Helm', 'richard.helm5@gmail.com', 1, '2018-02-10');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Ralph', 'Johnson', 'ralph.johnson5@gmail.com', 8, '2018-02-18');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('John', 'Vlissides', 'john.vlissides5@gmail.com', 3, '2018-02-28');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Dr. James', 'Gosling', 'james.gosling5@gmail.com', 4, '2018-03-03');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Magma', 'Lee', 'magma.lee5@gmail.com', 1, '2018-03-04');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Tornado', 'Roe', 'tornado.roe5@gmail.com', 1, '2018-03-05');
INSERT INTO customers (name, lastname, email, region_id, created_at) VALUES('Jade', 'Doe', 'jane.doe5@gmail.com', 4, '2018-03-06');